### ISSUE TITLE
Recommended approach for serverless deploys

### ISSUE THREAD

**Issue by adambartholomew** [codetheweb/serverless-step-functions-local#1]
Is there a recommendation of approach for performing serverless deploys?

The example listed in the Readme has the state's resource as a static string. This is fine for local development as the region and account Id are essentially ignored by the emulation of `serverless-offline`.

```
FirstState:
     Type: Task
     Resource: arn:aws:lambda:us-east-1:101010101010:function:hello
     Next: wait_using_seconds
```

However, you are not able to use any serverless variable replacement, or functions in the resource configuration. The YML parsed is raw and is sent directly to the create-state-machine function - which will fail with `Fn::` or `${}` syntax.

This makes it extremely difficult to deploy to multiple environments, and maintain local development configuration in the same place.

Are you open to pull requests to remedy this issue? I feel like this could be resolved with additional options exposed to the `custom.stepFunctions` configuration, although it may feel redundant at the time. Serverless-step-functions-offline does something similar in their usage example. https://github.com/vkkis93/serverless-step-functions-offline#usage
