### ISSUE TITLE
Support for .waitForTaskToken

### ISSUE THREAD

**Issue by czlowiek488** [codetheweb/serverless-step-functions-local#13]
I have this step:
```
Type: Task
    Resource: arn:aws:states:::lambda:invoke.waitForTaskToken
    Parameters:
        FunctionName: functionArn
        Payload: 
            token.$: $$.Task.Token
    End: true
```
Which is failing with error message:
`An error occurred while executing the state '' (entered at the event id #2). The JSONPath '$$.Task.Token' specified for the field 'token.$' could not be found in the input`
I can prepare PR however I am not sure how I should listen for `sendTaskSuccess`, `sendTaskFailure`.
If someone would be so kind to explain me how to listen for those things I will take care of the rest and prepare a PR.
