### ISSUE TITLE
AccountId not assigned correctly.

### ISSUE THREAD

**Issue by renejesusgv** [codetheweb/serverless-step-functions-local#24]
I'm facing problem, even though I am defining the value of my `accountId (000000000000)`, the state machines are built with a different `accountId (123456789012)` . 

```
    stepFunctionsLocal:
        accountId: "000000000000"
        region: us-east-1
```
```
-> $ aws stepfunctions list-state-machines --endpoint-url=http://localhost:8083
{
    "stateMachines": [
        {
            "stateMachineArn": "arn:aws:states:us-east-1:123456789012:stateMachine:local-myMachine",
            "name": "local-myMachine",
            "type": "EXPRESS",
            "creationDate": 1700375563.854
        }
    ]
}

```

**Comment by renejesusgv** [comment]
I solved the issue by defining the aws credentials as env variables: 
```
AWS_ACCESS_KEY_ID=fakeKey
AWS_SECRET_KEY=fakeSecret
```

**Comment by renejesusgv** [comment]
Fixed this by setting my account id as env var in my docker-compose.yml stepfunction service:
```
    stepfunctions:
        container_name: stepfunctions
        image: amazon/aws-stepfunctions-local:latest
        environment:
          - AWS_ACCESS_KEY_ID=fakeKey
          - AWS_SECRET_KEY=fakeSecret
          - AWS_ACCOUNT_ID=000000000000
```
