### ISSUE TITLE
Inaccessible host error after upgrading to node 18

### ISSUE THREAD

**Issue by cullylarson** [codetheweb/serverless-step-functions-local#25]
I started getting this error after upgrading to Node 18:

```
 UnknownEndpoint: Inaccessible host: `localhost' at port `8083'. This service may not be available in the `us-east-2' region.
```

I found a solution. Just posting in case someone else runs into this issue. The solution is to manually set `stepFunctionsEndpoint` to `http://127.0.0.1:8083`:

```yml
stepFunctionsLocal:
  # The default for stepFunctionsEndpoint is http://localhost:8083, but for
  # some reason `localhost` doesn't work after upgrading to node 18.
  stepFunctionsEndpoint: http://127.0.0.1:8083
```
