### ISSUE TITLE
ExecutionFailed for Lambda.ResourceNotFoundException

### ISSUE THREAD

**Issue by 535983297** [codetheweb/serverless-step-functions-local#3]
Thanks a lot for the repo!
I tried to create a sample according to the README said.
But got the error in the following. Did I set the wrong parameters?
```
offline: Attempt to invoke function 'hello' failed. Function does not exists.
[Serverless Step Functions Local]
[Serverless Step Functions Local] 2021-05-13 15:24:45.237: arn:aws:states:ap-southeast-1:101010101010:execution:StepFunctionSample:1313ef95-d8f5-4791-a438-ae17ca61c946 : {"Type":"LambdaFunctionFailed","PreviousEventId":4,"LambdaFunctionFailedEventDetails":{"Error":"Lambda.ResourceNotFoundException","Cause":"Function not found: hello (Service: AWSLambda; Status Code:
404; Error Code: ResourceNotFoundException; Request ID: null)"}}

[Serverless Step Functions Local]
[Serverless Step Functions Local] 2021-05-13 15:24:45.242: arn:aws:states:ap-southeast-1:101010101010:execution:StepFunctionSample:1313ef95-d8f5-4791-a438-ae17ca61c946 : {"Type":"ExecutionFailed","PreviousEventId":5,"ExecutionFailedEventDetails":{"Error":"Lambda.ResourceNotFoundException","Cause":"Function not found: hello (Service: AWSLambda; Status Code: 404; Error Code: ResourceNotFoundException; Request ID: null)"}}
```

Here is my serverless.yml.
```
plugins:
  - serverless-offline
  - serverless-offline-lambda
  - serverless-step-functions
  - serverless-step-functions-local

custom:
  stepFunctionsLocal:
    accountId: 101010101010
    region: ap-southeast-1
    lambdaEndpoint: http://localhost:3002
    TaskResourceMapping:
      FirstState: arn:aws:lambda:ap-southeast-1:101010101010:function:first-function

functions:
  first-function:
    handler: src/functions/stepFunctionLocalSample.firstFunction

stepFunctions:
  stateMachines:
    StepFunctionSample:
      definition:
        Comment: "An example of step function locally"
        StartAt: FirstState
        States:
          FirstState:
            Type: Task
            Resource: 
              Fn::GetAtt: [first-function, Arn]
            Next: done
          done:
            Type: Pass
            End: true   
```
