### ISSUE TITLE
Local Retry mechanism when throwing errors

### ISSUE THREAD

**Issue by richlloydmiles** [codetheweb/serverless-step-functions-local#5]
When a JavaScript error is thrown within a Task state that has a retry it ends the node server with an error.
Is there any way to avoid this, to replicate error handling on AWS locally?

My code is as follows:

serverless.yml
```
FinalState:
  Type: Task
  Resource: 
    Fn::GetAtt: [world, Arn]
  Retry:
  - ErrorEquals: ["States.ALL"]
    IntervalSeconds: 1
    MaxAttempts: 5
    BackoffRate: 2
```

world function in handler:

```
module.exports.world = async event => {
  const num = Math.floor(Math.random() * 2) + 1
  if (num === 1) {
    throw new Error('Failed')
  }

  return { message: 'Success', event }
}
```

(the function just basically generates a random number between one and two, if the number is 1 then it fails, so this function should fail 50% of the time).
